services:
  - type: web
    name: ai-data-cleaner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyA_DlEDZO-tArFm_xbBMpujW5Zr4A8aBEA
    plan: free
